name: Wheels

on: [push, pull_request, workflow_dispatch]

jobs:
  linux-latest:
    if: "!startsWith(github.ref, 'refs/tags/')"
    uses: ./.github/workflows/wheels-linux.yml
    with:
      build-commit: "main"
      artifacts-name: "wheels-latest"
